USE DATABASE LEAGUE_RECORDS;

USE SCHEMA SILVER;


WITH MATCH_LAST_INTERVAL AS (
    SELECT MATCH_ID,
        MAX(MINUTE) AS END_INTERVALSNOWFLAKE_SAMPLE_DATA
    FROM PLAYER_INTERVAL_SILVER
    GROUP BY MATCH_ID
), 
MATCH_STATS_AT_END AS (
    SELECT ML.MATCH_ID,
        SUM(PIV.KILLS) AS TOTAL_KILLS,
        SUM(PIV.)
    FROM MATCH_LAST_INTERVAL AS ML
    JOIN PLAYER_INTERVAL_SILVER AS PIV
        ON PIV.MATCH_ID = ML.MATCH_ID
        AND PIV.MINUTE = ML.END_INTERVAL
    GROUP BY ML.MATCH_ID
)

SELECT ML.MATCH_ID,
    ML.END_INTERVAL,
    PIV.KILLS,
    PIV.DEATHS,
    PIV.ASSISTS
FROM MATCH_LAST_INTERVAL AS ML
JOIN PLAYER_INTERVAL_SILVER AS PIV
    ON PIV.MATCH_ID = ML.MATCH_ID
    AND PIV.MINUTE = ML.END_INTERVAL
JOIN MATCHES_SUMMARY_SILVER AS MS
    ON MS.MATCH_ID = ML.MATCH_ID
GROUP BY ML.MATCH_ID
ORDER BY ML.MATCH_ID, PS.PARTICIPANT_POS_ID
;
