USE DATABASE LEAGUE_RECORDS;
USE SCHEMA GOLD;

WITH MATCH_LAST_INTERVAL AS (
    SELECT MATCH_ID, MAX(MINUTE) AS END_INTERVAL
    FROM SILVER.PLAYER_INTERVAL_SILVER
    GROUP BY MATCH_ID
),
MATCH_STATS_AT_END AS (
    SELECT
        ML.MATCH_ID,
        PIV.PARTICIPANT_POS_ID,
        PIV.KILLS,
        PIV.DEATHS,
        PIV.ASSISTS,
        (PIV.CS + PIV.JUNGLE_CS) AS CS,
        PIV.TOTAL_GOLD
    FROM MATCH_LAST_INTERVAL AS ML
    JOIN SILVER.PLAYER_INTERVAL_SILVER AS PIV
        ON PIV.MATCH_ID = ML.MATCH_ID
        AND PIV.MINUTE = ML.END_INTERVAL
),
PLAYER_MATCH AS (
    SELECT
        PS.CHAMPION,
        PS.LANE,
        (PS.TEAM = MAT.WINNING_TEAM) AS WIN,
        SE.KILLS,
        SE.DEATHS,
        SE.ASSISTS,
        (SE.KILLS + SE.ASSISTS)::DECIMAL / (SE.DEATHS + 1) AS KDA,
        SE.CS,
        SE.TOTAL_GOLD,
        SE.TOTAL_GOLD::DECIMAL / NULLIF(MAT.GAME_DURATION, 0) * 60 AS GOLD_PER_MIN,
        MAT.GAME_DURATION
    FROM MATCH_STATS_AT_END AS SE
    JOIN SILVER.MATCHES_SUMMARY_SILVER AS MAT
        ON MAT.MATCH_ID = SE.MATCH_ID
    JOIN SILVER.PLAYERS_SUMMARY_SILVER AS PS
        ON PS.MATCH_ID = SE.MATCH_ID
        AND PS.PARTICIPANT_POS_ID = SE.PARTICIPANT_POS_ID
),
CHAMPION_LANE_COUNTS AS (
    SELECT CHAMPION, LANE, COUNT(*) AS GAMES_IN_LANE
    FROM PLAYER_MATCH
    GROUP BY CHAMPION, LANE
),
LANE_TOTALS AS (
    SELECT LANE, COUNT(*) AS TOTAL_GAMES_IN_LANE
    FROM PLAYER_MATCH
    GROUP BY LANE
),
PRIMARY_LANE AS (
    SELECT
        CLC.CHAMPION,
        CLC.LANE                                                   AS PRIMARY_LANE,
        ROUND(CLC.GAMES_IN_LANE / LT.TOTAL_GAMES_IN_LANE::FLOAT, 4) AS PRIMARY_LANE_PICK_RATE,
        ROW_NUMBER() OVER (
            PARTITION BY CLC.CHAMPION ORDER BY CLC.GAMES_IN_LANE DESC
        ) AS LANE_RANK
    FROM CHAMPION_LANE_COUNTS AS CLC
    JOIN LANE_TOTALS AS LT ON LT.LANE = CLC.LANE
    QUALIFY LANE_RANK = 1
)
SELECT
    PM.CHAMPION,
    PL.PRIMARY_LANE,
    PL.PRIMARY_LANE_PICK_RATE,
    COUNT(*)                                   AS GAMES_PLAYED,
    SUM(IFF(PM.WIN, 1, 0))                     AS WINS,
    ROUND(SUM(IFF(PM.WIN, 1, 0)) / COUNT(*)::FLOAT, 4)   AS WIN_RATE,
    ROUND(AVG(PM.KILLS), 2)                    AS AVG_KILLS,
    ROUND(AVG(PM.DEATHS), 2)                   AS AVG_DEATHS,
    ROUND(AVG(PM.ASSISTS), 2)                  AS AVG_ASSISTS,
    ROUND(AVG(PM.KDA), 2)                      AS AVG_KDA,
    ROUND(AVG(PM.CS), 2)                       AS AVG_CS,
    ROUND(AVG(PM.TOTAL_GOLD), 0)               AS AVG_GOLD,
    ROUND(AVG(PM.GOLD_PER_MIN), 2)              AS AVG_GOLD_PER_MIN,
    ROUND(AVG(PM.GAME_DURATION), 0)             AS AVG_GAME_DURATION
FROM PLAYER_MATCH AS PM
JOIN PRIMARY_LANE AS PL ON PL.CHAMPION = PM.CHAMPION
GROUP BY PM.CHAMPION, PL.PRIMARY_LANE, PL.PRIMARY_LANE_PICK_RATE
ORDER BY GAMES_PLAYED DESC
;