USE DATABASE LEAGUE_RECORDS;
USE SCHEMA GOLD;
-------------------------------------------------------------------------------------------
    -- MATCH_STATS_SUMMARY: Match-grain summary. 
-------------------------------------------------------------------------------------------
WITH TEAM_FINAL AS (
    SELECT 
        -- Primary key
        TI.MATCH_ID,
        TI.TEAM,
        -- Stats
        TI.TEAM_KILLS,
        TI.TEAM_TOWERS,
        TI.TEAM_DRAGONS,
        TI.TEAM_VOID_GRUBS,
        TI.TEAM_HERALDS,
        TI.TEAM_BARONS,
        TI.TEAM_GOLD_DIFF,
    FROM SILVER.TEAM_INTERVAL_SILVER AS TI
    ---- Capture only the last minute interval per match --> A match's final statistics
    JOIN (
        SELECT MATCH_ID, MAX(MINUTE) AS MINUTE
        FROM SILVER.TEAM_INTERVAL_SILVER
        GROUP BY MATCH_ID
    ) AS LM 
        ON LM.MATCH_ID = TI.MATCH_ID
        AND LM.MINUTE = TI.MINUTE
),

PIVOT_TEAM_STATS AS (
    SELECT MATCH_ID,
        MAX(CASE WHEN TEAM = 'Blue' THEN TEAM_KILLS END) AS BLUE_KILLS,
        MAX(CASE WHEN TEAM = 'Red' THEN TEAM_KILLS END) AS RED_KILLS,
        MAX(CASE WHEN TEAM = 'Blue' THEN TEAM_TOWERS END) AS BLUE_TOWERS,
        MAX(CASE WHEN TEAM = 'Red' THEN TEAM_TOWERS END) AS RED_TOWERS,
        MAX(CASE WHEN TEAM = 'Blue' THEN TEAM_DRAGONS END) AS BLUE_DRAGONS,
        MAX(CASE WHEN TEAM = 'Red' THEN TEAM_DRAGONS END) AS RED_DRAGONS,
        MAX(CASE WHEN TEAM = 'Blue' THEN TEAM_VOID_GRUBS END) AS BLUE_VOID_GRUBS,
        MAX(CASE WHEN TEAM = 'Red' THEN TEAM_VOID_GRUBS END) AS RED_VOID_GRUBS,
        MAX(CASE WHEN TEAM = 'Blue' THEN TEAM_HERALDS END) AS BLUE_HERALDS,
        MAX(CASE WHEN TEAM = 'Red' THEN TEAM_HERALDS END) AS RED_HERALDS,
        MAX(CASE WHEN TEAM = 'Blue' THEN TEAM_BARONS END) AS BLUE_BARONS,
        MAX(CASE WHEN TEAM = 'Red' THEN TEAM_BARONS END) AS RED_BARONS,
        MAX(CASE WHEN TEAM = 'Blue' THEN TEAM_GOLD_DIFF END) AS BLUE_GOLD_DIFF,
        MAX(CASE WHEN TEAM = 'Red' THEN TEAM_GOLD_DIFF END) AS RED_GOLD_DIFF
    FROM TEAM_FINAL
    GROUP BY MATCH_ID
),

WINNING_GOLD_DIFF_CTE AS (
    SELECT 
        P.MATCH_ID,
        -- Keep only the gold diff of the winning team to report
        CASE 
            WHEN M.WINNING_TEAM = 'Blue' THEN P.BLUE_GOLD_DIFF
            WHEN M.WINNING_TEAM = 'Red'  THEN P.RED_GOLD_DIFF
        END AS WINNING_GOLD_DIFF
    FROM PIVOT_TEAM_STATS AS P
    JOIN SILVER.MATCHES_SUMMARY_SILVER AS M
        ON P.MATCH_ID = M.MATCH_ID
),

WITH_MATCH_SUMMARY AS (
    SELECT 
        -- Primary Key
        P.MATCH_ID,
        -- Context
        M.GAME_DURATION,
        M.GAME_DATE,
        M.WINNING_TEAM,        
        M.AVERAGE_RANK,
        -- Stats
        P.BLUE_KILLS,
        P.RED_KILLS,
        P.BLUE_TOWERS,
        P.RED_TOWERS,
        P.BLUE_DRAGONS,
        P.RED_DRAGONS,
        P.BLUE_VOID_GRUBS,
        P.RED_VOID_GRUBS,
        P.BLUE_HERALDS,
        P.RED_HERALDS,
        P.BLUE_BARONS,
        P.RED_BARONS,
        W.WINNING_GOLD_DIFF
    FROM PIVOT_TEAM_STATS AS P
    JOIN SILVER.MATCHES_SUMMARY_SILVER AS M
        ON P.MATCH_ID = M.MATCH_ID
    JOIN WINNING_GOLD_DIFF_CTE AS W
        ON P.MATCH_ID = W.MATCH_ID
)

SELECT *
FROM WITH_MATCH_SUMMARY
WHERE WINNING_GOLD_DIFF < 0
ORDER BY GAME_DATE DESC
;
