USE DATABASE LEAGUE_RECORDS;
USE SCHEMA GOLD;


-------------------------------------------------------------------------------------------
    -- MATCH_STATS_SUMMARY: Match-grain summary. 
-------------------------------------------------------------------------------------------
WITH MATCH_LAST_INTERVAL AS (
    SELECT MATCH_ID, MAX(MINUTE) AS END_INTERVAL
    FROM SILVER.TEAM_INTERVAL_SILVER
    GROUP BY MATCH_ID
),

TEAM_FINAL AS (
    SELECT 
        -- Primary Key
        TI.MATCH_ID, 
        TI.TEAM, 
        TI.TEAM_KILLS, 
        TI.TEAM_TOWERS,
        TI.TEAM_DRAGONS, 
        TI.TEAM_BARONS, 
        TI.TEAM_GOLD_DIFF
    FROM MATCH_LAST_INTERVAL AS ML
    JOIN SILVER.TEAM_INTERVAL_SILVER AS TI
        ON TI.MATCH_ID = ML.MATCH_ID 
        AND TI.MINUTE = ML.END_INTERVAL
)

SELECT
    -- Primary key
    MAT.MATCH_ID,
    -- Context
    MAT.GAME_DURATION,
    MAT.AVERAGE_RANK,
    MAT.WINNING_TEAM,
    MAT.GAME_DATE,
    MAX(IFF(TF.TEAM = 'Blue', TF.TEAM_KILLS, NULL))   AS BLUE_KILLS,
    MAX(IFF(TF.TEAM = 'Red',  TF.TEAM_KILLS, NULL))   AS RED_KILLS,
    MAX(IFF(TF.TEAM = 'Blue', TF.TEAM_TOWERS, NULL))  AS BLUE_TOWERS,
    MAX(IFF(TF.TEAM = 'Red',  TF.TEAM_TOWERS, NULL))  AS RED_TOWERS,
    MAX(IFF(TF.TEAM = 'Blue', TF.TEAM_DRAGONS, NULL)) AS BLUE_DRAGONS,
    MAX(IFF(TF.TEAM = 'Red',  TF.TEAM_DRAGONS, NULL)) AS RED_DRAGONS,
    MAX(IFF(TF.TEAM = 'Blue', TF.TEAM_BARONS, NULL))  AS BLUE_BARONS,
    MAX(IFF(TF.TEAM = 'Red',  TF.TEAM_BARONS, NULL))  AS RED_BARONS,
FROM SILVER.MATCHES_SUMMARY_SILVER AS MAT
LEFT JOIN TEAM_FINAL AS TF ON TF.MATCH_ID = MAT.MATCH_ID
GROUP BY MAT.MATCH_ID, MAT.GAME_DURATION, MAT.WINNING_TEAM, MAT.GAME_DATE,
         MAT.GAME_VERSION, MAT.AVERAGE_RANK
;
