USE DATABASE LEAGUE_RECORDS;
USE SCHEMA GOLD;

WITH MATCH_LAST_INTERVAL AS (
    SELECT MATCH_ID, MAX(MINUTE) AS END_INTERVAL
    FROM SILVER.PLAYER_INTERVAL_SILVER
    GROUP BY MATCH_ID
),

FINAL_ITEMS AS (
    SELECT
        ML.MATCH_ID,
        PIV.PARTICIPANT_POS_ID,
        PS.CHAMPION,
        PS.LANE,
        PIV.ITEM_0, PIV.ITEM_1, PIV.ITEM_2, PIV.ITEM_3,
        PIV.ITEM_4, PIV.ITEM_5, PIV.ITEM_6
    FROM MATCH_LAST_INTERVAL AS ML
    JOIN SILVER.PLAYER_INTERVAL_SILVER AS PIV
        ON PIV.MATCH_ID = ML.MATCH_ID
        AND PIV.MINUTE = ML.END_INTERVAL
    JOIN SILVER.PLAYERS_SUMMARY_SILVER AS PS
        ON PS.MATCH_ID = ML.MATCH_ID
        AND PS.PARTICIPANT_POS_ID = PIV.PARTICIPANT_POS_ID
),

PLAYER_ITEMS AS (
    SELECT MATCH_ID, PARTICIPANT_POS_ID, CHAMPION, LANE, 0 AS SLOT, ITEM_0 AS ITEM_NAME FROM FINAL_ITEMS WHERE ITEM_0 IS NOT NULL
    UNION ALL
    SELECT MATCH_ID, PARTICIPANT_POS_ID, CHAMPION, LANE, 1, ITEM_1 FROM FINAL_ITEMS WHERE ITEM_1 IS NOT NULL
    UNION ALL
    SELECT MATCH_ID, PARTICIPANT_POS_ID, CHAMPION, LANE, 2, ITEM_2 FROM FINAL_ITEMS WHERE ITEM_2 IS NOT NULL
    UNION ALL
    SELECT MATCH_ID, PARTICIPANT_POS_ID, CHAMPION, LANE, 3, ITEM_3 FROM FINAL_ITEMS WHERE ITEM_3 IS NOT NULL
    UNION ALL
    SELECT MATCH_ID, PARTICIPANT_POS_ID, CHAMPION, LANE, 4, ITEM_4 FROM FINAL_ITEMS WHERE ITEM_4 IS NOT NULL
    UNION ALL
    SELECT MATCH_ID, PARTICIPANT_POS_ID, CHAMPION, LANE, 5, ITEM_5 FROM FINAL_ITEMS WHERE ITEM_5 IS NOT NULL
    UNION ALL
    SELECT MATCH_ID, PARTICIPANT_POS_ID, CHAMPION, LANE, 6, ITEM_6 FROM FINAL_ITEMS WHERE ITEM_6 IS NOT NULL
),

ITEM_FREQ AS (
    SELECT CHAMPION, LANE, SLOT, ITEM_NAME, COUNT(*) AS ITEM_COUNT
    FROM PLAYER_ITEMS
    GROUP BY CHAMPION, LANE, SLOT, ITEM_NAME
),

CO_OCCURRENCE AS (
    -- Slot-ordered pairs only (B bought strictly after A), keeps "what comes next"
    -- semantics and avoids double-counting both directions of the same pair.
    SELECT
        A.CHAMPION, A.LANE,
        A.ITEM_NAME AS BASE_ITEM, A.SLOT AS BASE_SLOT,
        B.ITEM_NAME AS RECOMMENDED_ITEM, B.SLOT AS RECOMMENDED_SLOT,
        COUNT(*)    AS CO_PURCHASE_COUNT
    FROM PLAYER_ITEMS A
    JOIN PLAYER_ITEMS B
        ON A.MATCH_ID = B.MATCH_ID
        AND A.PARTICIPANT_POS_ID = B.PARTICIPANT_POS_ID
        AND B.SLOT > A.SLOT
        AND A.ITEM_NAME != B.ITEM_NAME
    GROUP BY A.CHAMPION, A.LANE, A.ITEM_NAME, A.SLOT, B.ITEM_NAME, B.SLOT
),
BASKETS AS (
    SELECT CHAMPION, LANE, COUNT(*) AS TOTAL_BASKETS
    FROM (SELECT DISTINCT MATCH_ID, PARTICIPANT_POS_ID, CHAMPION, LANE FROM PLAYER_ITEMS)
    GROUP BY CHAMPION, LANE
)

SELECT
    CO.CHAMPION,
    CO.LANE,
    CO.BASE_ITEM,
    CO.BASE_SLOT,
    CO.RECOMMENDED_ITEM,
    CO.RECOMMENDED_SLOT,
    CO.CO_PURCHASE_COUNT,
    IFB.ITEM_COUNT                                              AS BASE_ITEM_COUNT,
    ROUND(CO.CO_PURCHASE_COUNT / BK.TOTAL_BASKETS::FLOAT, 4)     AS SUPPORT,
    ROUND(CO.CO_PURCHASE_COUNT / IFB.ITEM_COUNT::FLOAT, 4)       AS CONFIDENCE,
    ROUND(
        (CO.CO_PURCHASE_COUNT / IFB.ITEM_COUNT::FLOAT)
            / (IFR.ITEM_COUNT / BK.TOTAL_BASKETS::FLOAT)
    , 4)                                                          AS LIFT,
    ROW_NUMBER() OVER (
        PARTITION BY CO.CHAMPION, CO.LANE, CO.BASE_ITEM, CO.BASE_SLOT
        ORDER BY (CO.CO_PURCHASE_COUNT / IFB.ITEM_COUNT::FLOAT)
            / (IFR.ITEM_COUNT / BK.TOTAL_BASKETS::FLOAT) DESC
    ) AS RANK
FROM CO_OCCURRENCE CO
JOIN ITEM_FREQ IFB
    ON IFB.CHAMPION = CO.CHAMPION AND IFB.LANE = CO.LANE
    AND IFB.SLOT = CO.BASE_SLOT AND IFB.ITEM_NAME = CO.BASE_ITEM
JOIN ITEM_FREQ IFR
    ON IFR.CHAMPION = CO.CHAMPION AND IFR.LANE = CO.LANE
    AND IFR.SLOT = CO.RECOMMENDED_SLOT AND IFR.ITEM_NAME = CO.RECOMMENDED_ITEM
JOIN BASKETS BK
    ON BK.CHAMPION = CO.CHAMPION AND BK.LANE = CO.LANE
QUALIFY IFB.ITEM_COUNT >= 10   -- min-support floor on base item, tune at implementation
ORDER BY CO.CHAMPION, CO.LANE, CO.BASE_SLOT, CO.BASE_ITEM, RANK
;