USE DATABASE LEAGUE_RECORDS;
USE SCHEMA GOLD;

-- CREATE OR REPLACE DYNAMIC TABLE GOLD.ITEM_RECOMMEND
--     TARGET_LAG = '1 hour'
--     WAREHOUSE = COMPUTE_WH
-- AS
WITH MATCH_LAST_INTERVAL AS (
    SELECT MATCH_ID, MAX(MINUTE) AS END_INTERVAL
    FROM SILVER.PLAYER_INTERVAL_SILVER
    GROUP BY MATCH_ID
),

FINAL_SNAPSHOT AS (
    SELECT
        ML.MATCH_ID,
        PIV.PARTICIPANT_POS_ID,
        PIV.KILLS, PIV.DEATHS, PIV.ASSISTS,
        PIV.ITEM_0, PIV.ITEM_1, PIV.ITEM_2, PIV.ITEM_3,
        PIV.ITEM_4, PIV.ITEM_5, PIV.ITEM_6,
        (PS.TEAM = MAT.WINNING_TEAM) AS WIN
    FROM MATCH_LAST_INTERVAL AS ML
    JOIN SILVER.PLAYER_INTERVAL_SILVER AS PIV
        ON PIV.MATCH_ID = ML.MATCH_ID
        AND PIV.MINUTE = ML.END_INTERVAL
    JOIN SILVER.MATCHES_SUMMARY_SILVER AS MAT
        ON MAT.MATCH_ID = ML.MATCH_ID
    JOIN SILVER.PLAYERS_SUMMARY_SILVER AS PS
        ON PS.MATCH_ID = ML.MATCH_ID
        AND PS.PARTICIPANT_POS_ID = PIV.PARTICIPANT_POS_ID
),

PLAYER_ITEMS AS (
    SELECT DISTINCT MATCH_ID, PARTICIPANT_POS_ID, KILLS, DEATHS, ASSISTS, WIN, ITEM_NAME
    FROM (
        SELECT MATCH_ID, PARTICIPANT_POS_ID, KILLS, DEATHS, ASSISTS, WIN, ITEM_0 AS ITEM_NAME FROM FINAL_SNAPSHOT WHERE ITEM_0 IS NOT NULL
        UNION ALL
        SELECT MATCH_ID, PARTICIPANT_POS_ID, KILLS, DEATHS, ASSISTS, WIN, ITEM_1 FROM FINAL_SNAPSHOT WHERE ITEM_1 IS NOT NULL
        UNION ALL
        SELECT MATCH_ID, PARTICIPANT_POS_ID, KILLS, DEATHS, ASSISTS, WIN, ITEM_2 FROM FINAL_SNAPSHOT WHERE ITEM_2 IS NOT NULL
        UNION ALL
        SELECT MATCH_ID, PARTICIPANT_POS_ID, KILLS, DEATHS, ASSISTS, WIN, ITEM_3 FROM FINAL_SNAPSHOT WHERE ITEM_3 IS NOT NULL
        UNION ALL
        SELECT MATCH_ID, PARTICIPANT_POS_ID, KILLS, DEATHS, ASSISTS, WIN, ITEM_4 FROM FINAL_SNAPSHOT WHERE ITEM_4 IS NOT NULL
        UNION ALL
        SELECT MATCH_ID, PARTICIPANT_POS_ID, KILLS, DEATHS, ASSISTS, WIN, ITEM_5 FROM FINAL_SNAPSHOT WHERE ITEM_5 IS NOT NULL
        UNION ALL
        SELECT MATCH_ID, PARTICIPANT_POS_ID, KILLS, DEATHS, ASSISTS, WIN, ITEM_6 FROM FINAL_SNAPSHOT WHERE ITEM_6 IS NOT NULL
    )
),

ITEM_STATS AS (
    SELECT
        ITEM_NAME,
        COUNT(*)                                                AS PLAYERS_PURCHASED,
        SUM(IFF(WIN, 1, 0))                                      AS WINS_WITH_ITEM,
        ROUND(AVG((KILLS + ASSISTS) / GREATEST(DEATHS, 1)), 2)   AS AVG_KDA
    FROM PLAYER_ITEMS
    GROUP BY ITEM_NAME
),

TOTAL_PLAYERS AS (
    SELECT COUNT(*) AS TOTAL_PLAYER_MATCHES
    FROM SILVER.PLAYERS_SUMMARY_SILVER
),
-- Half-volume self-join: only compute each unordered pair once (A < B)
CO_OCCURRENCE AS (
    SELECT
        A.ITEM_NAME AS ITEM,
        B.ITEM_NAME AS CO_ITEM,
        COUNT(*)    AS CO_PURCHASE_COUNT
    FROM PLAYER_ITEMS A
    JOIN PLAYER_ITEMS B
        ON A.MATCH_ID = B.MATCH_ID
        AND A.PARTICIPANT_POS_ID = B.PARTICIPANT_POS_ID
        AND A.ITEM_NAME < B.ITEM_NAME
    GROUP BY A.ITEM_NAME, B.ITEM_NAME
),
-- Re-expand to both directions (cheap now: operates on aggregated pairs, not raw rows)
CO_OCCURRENCE_BOTH_DIRECTIONS AS (
    SELECT ITEM, CO_ITEM, CO_PURCHASE_COUNT FROM CO_OCCURRENCE
    UNION ALL
    SELECT CO_ITEM AS ITEM, ITEM AS CO_ITEM, CO_PURCHASE_COUNT FROM CO_OCCURRENCE
),
RANKED_CO_OCCURRENCE AS (
    SELECT
        ITEM, CO_ITEM,
        ROW_NUMBER() OVER (
            PARTITION BY ITEM ORDER BY CO_PURCHASE_COUNT DESC
        ) AS CO_RANK
    FROM CO_OCCURRENCE_BOTH_DIRECTIONS
    QUALIFY CO_RANK <= 3
),
TOP3_WIDE AS (
    SELECT
        ITEM,
        MAX(IFF(CO_RANK = 1, CO_ITEM, NULL)) AS TOP_ITEM_1,
        MAX(IFF(CO_RANK = 2, CO_ITEM, NULL)) AS TOP_ITEM_2,
        MAX(IFF(CO_RANK = 3, CO_ITEM, NULL)) AS TOP_ITEM_3
    FROM RANKED_CO_OCCURRENCE
    GROUP BY ITEM
),
-- First-purchase interval: scan every minute (not just the final snapshot) to find the
-- earliest MINUTE each item appears in any slot, per player-match.
ITEM_APPEARANCES AS (
    SELECT DISTINCT MATCH_ID, PARTICIPANT_POS_ID, MINUTE, ITEM_NAME
    FROM (
        SELECT MATCH_ID, PARTICIPANT_POS_ID, MINUTE, ITEM_0 AS ITEM_NAME FROM SILVER.PLAYER_INTERVAL_SILVER WHERE ITEM_0 IS NOT NULL
        UNION ALL
        SELECT MATCH_ID, PARTICIPANT_POS_ID, MINUTE, ITEM_1 FROM SILVER.PLAYER_INTERVAL_SILVER WHERE ITEM_1 IS NOT NULL
        UNION ALL
        SELECT MATCH_ID, PARTICIPANT_POS_ID, MINUTE, ITEM_2 FROM SILVER.PLAYER_INTERVAL_SILVER WHERE ITEM_2 IS NOT NULL
        UNION ALL
        SELECT MATCH_ID, PARTICIPANT_POS_ID, MINUTE, ITEM_3 FROM SILVER.PLAYER_INTERVAL_SILVER WHERE ITEM_3 IS NOT NULL
        UNION ALL
        SELECT MATCH_ID, PARTICIPANT_POS_ID, MINUTE, ITEM_4 FROM SILVER.PLAYER_INTERVAL_SILVER WHERE ITEM_4 IS NOT NULL
        UNION ALL
        SELECT MATCH_ID, PARTICIPANT_POS_ID, MINUTE, ITEM_5 FROM SILVER.PLAYER_INTERVAL_SILVER WHERE ITEM_5 IS NOT NULL
        UNION ALL
        SELECT MATCH_ID, PARTICIPANT_POS_ID, MINUTE, ITEM_6 FROM SILVER.PLAYER_INTERVAL_SILVER WHERE ITEM_6 IS NOT NULL
    )
),

FIRST_PURCHASE AS (
    SELECT MATCH_ID, PARTICIPANT_POS_ID, ITEM_NAME, MIN(MINUTE) AS FIRST_MINUTE
    FROM ITEM_APPEARANCES
    GROUP BY MATCH_ID, PARTICIPANT_POS_ID, ITEM_NAME
),

FIRST_PURCHASE_COUNTS AS (
    SELECT ITEM_NAME, FIRST_MINUTE, COUNT(*) AS CNT
    FROM FIRST_PURCHASE
    GROUP BY ITEM_NAME, FIRST_MINUTE
),

MOST_COMMON_FIRST_PURCHASE AS (
    SELECT
        ITEM_NAME,
        FIRST_MINUTE AS MOST_COMMON_FIRST_PURCHASE_MINUTE,
        ROW_NUMBER() OVER (
            PARTITION BY ITEM_NAME ORDER BY CNT DESC
        ) AS FIRST_MINUTE_RANK
    FROM FIRST_PURCHASE_COUNTS
    QUALIFY FIRST_MINUTE_RANK = 1
),

ITEM_STATS_FINAL AS (
    SELECT
        IS_.ITEM_NAME                                                          AS ITEM,
        ROUND(IS_.PLAYERS_PURCHASED / TP.TOTAL_PLAYER_MATCHES::FLOAT, 4)       AS PLAYER_PURCHASE_RATE,
        ROUND(IS_.WINS_WITH_ITEM / IS_.PLAYERS_PURCHASED::FLOAT, 4)            AS WIN_RATE,
        IS_.AVG_KDA,
        MCFP.MOST_COMMON_FIRST_PURCHASE_MINUTE,
        T3.TOP_ITEM_1,
        T3.TOP_ITEM_2,
        T3.TOP_ITEM_3
    FROM ITEM_STATS AS IS_
    CROSS JOIN TOTAL_PLAYERS AS TP
    LEFT JOIN TOP3_WIDE AS T3 ON T3.ITEM = IS_.ITEM_NAME
    LEFT JOIN MOST_COMMON_FIRST_PURCHASE AS MCFP ON MCFP.ITEM_NAME = IS_.ITEM_NAME
)

SELECT *
FROM ITEM_STATS_FINAL
;
