-------------------------------------------------------------------------------------------
    -- ANALYTICS LAYER: Fact and Dimension Views
-------------------------------------------------------------------------------------------
USE WAREHOUSE DV_COMPUTE_WH;
USE DATABASE LEAGUE_RECORDS;
USE SCHEMA L30_ID;

---------- SKIPPING L20_BDV STEPS...

---------- FACT VIEW
    -- player_intervals_kda
CREATE OR REPLACE VIEW DIM_INTERVALS_KDA AS
SELECT 
    SHA1_HUB_PLAYER_INTERVAL AS PLAYER_INTERVAL_ID, MINUTE,
    KILLS, DEATHS, ASSISTS
FROM L20_BDV.HUB_PLAYER_INTERVALS 
JOIN L20_BDV.SAT_INTERVALS_KDA USING(SHA1_HUB_PLAYER_INTERVAL);


CREATE OR REPLACE VIEW DIM_INTERVALS_CS AS
SELECT 
    SHA1_HUB_PLAYER_INTERVAL AS PLAYER_INTERVAL_ID, MINUTE,
    CS, JUNGLE_CS
FROM L20_BDV.HUB_PLAYER_INTERVALS 
JOIN L20_BDV.SAT_INTERVALS_ECONOMY USING(SHA1_HUB_PLAYER_INTERVAL);


CREATE OR REPLACE VIEW DIM_INTERVALS_ECON AS
SELECT 
    SHA1_HUB_PLAYER_INTERVAL AS PLAYER_INTERVAL_ID, MINUTE,
	CURRENT_GOLD,
	TOTAL_GOLD,
	GOLD_DIFF,
	LEVEL,
	XP,
	XP_DIFF
FROM L20_BDV.HUB_PLAYER_INTERVALS 
JOIN L20_BDV.SAT_INTERVALS_ECONOMY USING(SHA1_HUB_PLAYER_INTERVAL);


CREATE OR REPLACE VIEW DIM_INTERVALS_ITEMS AS
SELECT 
    SHA1_HUB_PLAYER_INTERVAL AS PLAYER_INTERVAL_ID, MINUTE,
    ITEM_0, ITEM_1, ITEM_2, ITEM_3, ITEM_4, ITEM_5, ITEM_6
FROM L20_BDV.HUB_PLAYER_INTERVALS 
JOIN L20_BDV.SAT_INTERVALS_ITEM USING(SHA1_HUB_PLAYER_INTERVAL);


CREATE OR REPLACE VIEW DIM_INTERVALS_DRAGONS AS 
SELECT DISTINCT
    SHA1_HUB_TEAM_INTERVAL AS TEAM_INTERVAL_ID, MINUTE,
    TEAM_DRAGONS_FIRE,
    TEAM_DRAGONS_WATER,
    TEAM_DRAGONS_EARTH,
    TEAM_DRAGONS_AIR,
    TEAM_DRAGONS_CHEMTECH,
    TEAM_DRAGONS_HEXTECH
FROM L20_BDV.HUB_TEAM_INTERVALS 
JOIN L20_BDV.SAT_TEAM_INTERVALS_OBJV USING(SHA1_HUB_TEAM_INTERVAL);


CREATE OR REPLACE VIEW DIM_INTERVALS_OBJ AS 
SELECT DISTINCT
    SHA1_HUB_TEAM_INTERVAL AS TEAM_INTERVAL_ID, MINUTE,
    TEAM_DRAGONS,
    TEAM_BARONS,
    TEAM_VOID_GRUBS,
    TEAM_HERALDS,
    TEAM_INHIBITORS,
    TEAM_TOWERS
FROM L20_BDV.HUB_TEAM_INTERVALS 
JOIN L20_BDV.SAT_TEAM_INTERVALS_OBJV USING(SHA1_HUB_TEAM_INTERVAL);


CREATE OR REPLACE VIEW DIM_INTERVALS_STAT AS 
SELECT DISTINCT
    SHA1_HUB_TEAM_INTERVAL AS TEAM_INTERVAL_ID, MINUTE,
    TEAM_KILLS, TEAM_GOLD_DIFF
FROM L20_BDV.HUB_TEAM_INTERVALS 
JOIN L20_BDV.SAT_TEAM_INTERVALS_OBJV USING(SHA1_HUB_TEAM_INTERVAL);


CREATE OR REPLACE VIEW FCT_INTERVALS AS 
SELECT 
    SHA1_LNK_TEAM_PLAYER_INTERVAL AS ID,
    SHA1_HUB_PLAYER_INTERVAL AS PLAYER_INTERVAL_ID,
    SHA1_HUB_TEAM_INTERVAL AS TEAM_INTERVAL_ID,
    MATCH_ID, 
    PLAYER_ID
FROM L20_BDV.LNK_PLAYER_TEAM_INTERVALS
JOIN L20_BDV.HUB_PLAYER_INTERVALS USING(SHA1_HUB_PLAYER_INTERVAL);