USE SCHEMA SILVER;


CREATE OR REPLACE VIEW SILVER.MATCH_INTERVALS_BRONZE_STM_TO_SILVER AS
-------------------------------------------------------------------------------------------
    -- 01. CLEANING: Cleaning and transformation
-------------------------------------------------------------------------------------------
WITH CLEANING AS (
    SELECT
        TRY_TO_NUMBER(ID) AS ID,
        UPPER(MATCH_ID) AS MATCH_ID,
        -- PLAYER_ID 3210 --> PARTICIPANT_POS_ID = 1 // PLAYER_ID 3156 --> PARTICIPANT_POS_ID = 6
        ((TRY_TO_NUMBER(PLAYER_ID) - 1) % 10) + 1 AS PARTICIPANT_POS_ID,
        -- Player 1-5 --> 'Blue' // Player 6-10 --> 'Red'
        CASE
            WHEN ((TRY_TO_NUMBER(PLAYER_ID) - 1) % 10) + 1 BETWEEN 1 AND 5 THEN 'Blue'
            WHEN ((TRY_TO_NUMBER(PLAYER_ID) - 1) % 10) + 1 BETWEEN 6 AND 10 THEN 'Red'
            ELSE NULL
        END AS TEAM,
        -- Clamp to interval of 5
        VALID_NUM_RANGE(
            ROUND(TRY_TO_NUMBER(MINUTE) / 5.0) * 5,
            0, 1E4
        ) AS MINUTE,
        -- Economy
        TRY_TO_NUMBER(CURRENT_GOLD) AS CURRENT_GOLD,
        VALID_NUM_RANGE(TRY_TO_NUMBER(TOTAL_GOLD), 0, 1E9) AS TOTAL_GOLD,
        VALID_NUM_RANGE(TRY_TO_NUMBER(CS), 0, 1E4) AS CS,
        VALID_NUM_RANGE(TRY_TO_NUMBER(JUNGLE_CS), 0, 1E4) AS JUNGLE_CS,
        VALID_NUM_RANGE(TRY_TO_NUMBER(XP), 0, 1E9) AS XP,
        VALID_NUM_RANGE(TRY_TO_NUMBER(LEVEL), 0, 20) AS LEVEL,
        -- KDA
        VALID_NUM_RANGE(TRY_TO_NUMBER(KILLS), 0, 1E3) AS KILLS,
        VALID_NUM_RANGE(TRY_TO_NUMBER(DEATHS), 0, 1E3) AS DEATHS,
        VALID_NUM_RANGE(TRY_TO_NUMBER(ASSISTS), 0, 1E3) AS ASSISTS,
        -- Nullify 0 (No items)
        NULLIF(TRY_TO_NUMBER(ITEM_0), 0) AS ITEM_0,
        NULLIF(TRY_TO_NUMBER(ITEM_1), 0) AS ITEM_1,
        NULLIF(TRY_TO_NUMBER(ITEM_2), 0) AS ITEM_2,
        NULLIF(TRY_TO_NUMBER(ITEM_3), 0) AS ITEM_3,
        NULLIF(TRY_TO_NUMBER(ITEM_4), 0) AS ITEM_4,
        NULLIF(TRY_TO_NUMBER(ITEM_5), 0) AS ITEM_5,
        NULLIF(TRY_TO_NUMBER(ITEM_6), 0) AS ITEM_6,
        -- Team's objective
        VALID_NUM_RANGE(TRY_TO_NUMBER(TEAM_KILLS), 0, 1E4) AS TEAM_KILLS,
        VALID_NUM_RANGE(TRY_TO_NUMBER(TEAM_INHIBITORS), 0, 1E2) AS TEAM_INHIBITORS,
        VALID_NUM_RANGE(TRY_TO_NUMBER(TEAM_TOWERS), 0, 1E2) AS TEAM_TOWERS,
        VALID_NUM_RANGE(TRY_TO_NUMBER(TEAM_DRAGONS_FIRE), 0, 4) AS TEAM_DRAGONS_FIRE,
        VALID_NUM_RANGE(TRY_TO_NUMBER(TEAM_DRAGONS_WATER), 0, 4) AS TEAM_DRAGONS_WATER,
        VALID_NUM_RANGE(TRY_TO_NUMBER(TEAM_DRAGONS_EARTH), 0, 4) AS TEAM_DRAGONS_EARTH,
        VALID_NUM_RANGE(TRY_TO_NUMBER(TEAM_DRAGONS_AIR), 0, 4) AS TEAM_DRAGONS_AIR,
        VALID_NUM_RANGE(TRY_TO_NUMBER(TEAM_DRAGONS_CHEMTECH), 0, 4) AS TEAM_DRAGONS_CHEMTECH,
        VALID_NUM_RANGE(TRY_TO_NUMBER(TEAM_DRAGONS_HEXTECH), 0, 4) AS TEAM_DRAGONS_HEXTECH,
        VALID_NUM_RANGE(TRY_TO_NUMBER(TEAM_DRAGONS), 0, 1E2) AS TEAM_DRAGONS,
        VALID_NUM_RANGE(TRY_TO_NUMBER(TEAM_BARONS), 0, 1E2) AS TEAM_BARONS,
        VALID_NUM_RANGE(TRY_TO_NUMBER(TEAM_VOID_GRUBS), 0, 1E2) AS TEAM_VOID_GRUBS,
        VALID_NUM_RANGE(TRY_TO_NUMBER(TEAM_HERALDS), 0, 1E2) AS TEAM_HERALDS,
        -- Diffs
        TRY_TO_NUMBER(GOLD_DIFF) AS GOLD_DIFF,
        TRY_TO_NUMBER(XP_DIFF) AS XP_DIFF,
        TRY_TO_NUMBER(TEAM_GOLD_DIFF) AS TEAM_GOLD_DIFF
    FROM BRONZE.MATCH_INTERVALS_BRONZE_STM
)
-------------------------------------------------------------------------------------------
    -- 02. FINAL_SELECT: pass BASE straight through, no imputation.
    -- Missing/out-of-range values stay NULL rather than being filled with an average.
-------------------------------------------------------------------------------------------
SELECT
    -- Primary key
    B.ID,
    -- Composite key
    B.MATCH_ID,
    B.PARTICIPANT_POS_ID,
    B.TEAM,
    B.MINUTE,
    -- Economy
    B.CURRENT_GOLD,
    B.TOTAL_GOLD,
    B.CS,
    B.JUNGLE_CS,
    B.XP,
    B.LEVEL,
    -- KDA
    B.KILLS,
    B.DEATHS,
    B.ASSISTS,
    -- Items
    B.ITEM_0,
    B.ITEM_1,
    B.ITEM_2,
    B.ITEM_3,
    B.ITEM_4,
    B.ITEM_5,
    B.ITEM_6,
    -- Team's Objective
    B.TEAM_KILLS,
    B.TEAM_INHIBITORS,
    B.TEAM_TOWERS,
    B.TEAM_DRAGONS_FIRE,
    B.TEAM_DRAGONS_WATER,
    B.TEAM_DRAGONS_EARTH,
    B.TEAM_DRAGONS_AIR,
    B.TEAM_DRAGONS_CHEMTECH,
    B.TEAM_DRAGONS_HEXTECH,
    B.TEAM_DRAGONS,
    B.TEAM_BARONS,
    B.TEAM_VOID_GRUBS,
    B.TEAM_HERALDS,
    -- Diffs
    B.GOLD_DIFF,
    B.XP_DIFF,
    B.TEAM_GOLD_DIFF
FROM CLEANING AS B
;
