-- Deploy role_importance Streamlit app as warehouse runtime via Git repository
-- Co-authored with CoCo

-- Step 1: Create Git repository stage (uses existing API integration and secret)
CREATE GIT REPOSITORY IF NOT EXISTS LEAGUE_RECORDS.GOLD.LEAGUE_SNOWFLAKE_REPO
  API_INTEGRATION = GITHUB_TOTORI_YOYORI
  GIT_CREDENTIALS = "USER$FLANCAFEVANILLA".PUBLIC.GITHUB_PORTFOLIO_CONNECT_PAT
  ORIGIN = 'https://github.com/TotoriYoyori/league-snowflake.git';

-- Step 2: Fetch latest from remote
ALTER GIT REPOSITORY LEAGUE_RECORDS.GOLD.LEAGUE_SNOWFLAKE_REPO FETCH;

-- Step 3: Drop existing app
DROP STREAMLIT IF EXISTS LEAGUE_RECORDS.GOLD.ROLE_IMPORTANCE;

-- Step 4: Create with warehouse runtime from Git repo
CREATE STREAMLIT LEAGUE_RECORDS.GOLD.ROLE_IMPORTANCE
  FROM @LEAGUE_RECORDS.GOLD.LEAGUE_SNOWFLAKE_REPO/branches/main/app/role_importance/
  MAIN_FILE = 'streamlit_app.py'
  QUERY_WAREHOUSE = COMPUTE_WH
  TITLE = 'LANE GOLD-DIFF WIN COEFFICIENT TRACKER';

-- Step 5: Publish
ALTER STREAMLIT LEAGUE_RECORDS.GOLD.ROLE_IMPORTANCE ADD LIVE VERSION FROM LAST;

-- Future updates: just run these two lines after pushing to GitHub
-- ALTER GIT REPOSITORY LEAGUE_RECORDS.GOLD.LEAGUE_SNOWFLAKE_REPO FETCH;
-- ALTER STREAMLIT LEAGUE_RECORDS.GOLD.ROLE_IMPORTANCE PULL;

DESCRIBE SECRET GITHUB_PORTFOLIO_CONNECT_PAT;