-- 1. Function to read state of database and schemas
USE DATABASE LEAGUE_RECORDS;

USE SCHEMA PUBLIC;

CREATE PROCEDURE EXAMINE_DB_SCHEMAS(DB_NAME VARCHAR)
RETURNS TABLE (
    NAME VARCHAR, 
    COMMENT VARCHAR, 
    CREATED_ON TIMESTAMP_LTZ
)
LANGUAGE SQL
AS
  $$
    BEGIN
      SHOW SCHEMAS IN DATABASE IDENTIFIER(:DB_NAME);
      LET rs RESULTSET := (
        SELECT 
            "name"::VARCHAR AS NAME, 
            "comment"::VARCHAR AS COMMENT, 
            "created_on"::TIMESTAMP_LTZ AS CREATED_ON
        FROM TABLE(
            RESULT_SCAN(LAST_QUERY_ID())
        )
      );
      RETURN TABLE(rs);
    END;
  $$
;

CALL EXAMINE_DB_SCHEMAS('LEAGUE_RECORDS');


-- 2. Examine Azure storage integration
SHOW STORAGE INTEGRATIONS;


-- 3. Examine file formats
SHOW FILE FORMATS IN DATABASE LEAGUE_RECORDS;


-- 4. Examine stages
SHOW STAGES IN DATABASE LEAGUE_RECORDS;
