-------------------------------------------------------------------------------------------
    -- 0. DECLARE WORKING CONTEXT
-------------------------------------------------------------------------------------------
USE DATABASE LEAGUE_RECORDS;

USE SCHEMA L20_ID;


-------------------------------------------------------------------------------------------
    -- 1. TASK: Populate partition tables from L10_RDV when new data arrives
    -- Reads from stream on SAT_INTERVALS, joins with HUB_INTERVALS for context columns,
    -- then inserts into all four partition tables.
-------------------------------------------------------------------------------------------
CREATE OR REPLACE TASK POPULATE_INTERVAL_PARTITIONS
    WAREHOUSE = DV_COMPUTE_WH
    SCHEDULE = '1 minute'
WHEN SYSTEM$STREAM_HAS_DATA('L20_ID.SAT_INTERVALS_STRM_ID')
AS
EXECUTE IMMEDIATE
$$
BEGIN
    -- KDA
    INSERT INTO INTERVALS_KDA (ID, MATCH_ID, PLAYER_ID, MINUTE, KILLS, DEATHS, ASSISTS, KDA_RATIO)
    SELECT
        H.ID, H.MATCH_ID, H.PLAYER_ID, H.MINUTE,
        S.KILLS, S.DEATHS, S.ASSISTS,
        (S.KILLS + S.ASSISTS) / NULLIFZERO(S.DEATHS)
    FROM SAT_INTERVALS_STRM_ID S
    JOIN L10_RDV.HUB_INTERVALS H ON S.SHA1_HUB_INTERVAL = H.SHA1_HUB_INTERVAL;

    -- Economy
    INSERT INTO INTERVALS_ECONOMY (ID, MATCH_ID, PLAYER_ID, MINUTE, CURRENT_GOLD, TOTAL_GOLD, CS, JUNGLE_CS, XP, LEVEL, GOLD_DIFF, XP_DIFF, NET_CS, GOLD_PER_MIN)
    SELECT
        H.ID, H.MATCH_ID, H.PLAYER_ID, H.MINUTE,
        S.CURRENT_GOLD, S.TOTAL_GOLD, S.CS, S.JUNGLE_CS, S.XP, S.LEVEL,
        S.GOLD_DIFF, S.XP_DIFF,
        S.CS + S.JUNGLE_CS,
        S.TOTAL_GOLD / NULLIFZERO(H.MINUTE)
    FROM SAT_INTERVALS_STRM_ID S
    JOIN L10_RDV.HUB_INTERVALS H ON S.SHA1_HUB_INTERVAL = H.SHA1_HUB_INTERVAL;

    -- Items
    INSERT INTO INTERVALS_ITEMS (ID, MATCH_ID, PLAYER_ID, MINUTE, ITEM_0, ITEM_1, ITEM_2, ITEM_3, ITEM_4, ITEM_5, ITEM_6)
    SELECT
        H.ID, H.MATCH_ID, H.PLAYER_ID, H.MINUTE,
        S.ITEM_0, S.ITEM_1, S.ITEM_2, S.ITEM_3, S.ITEM_4, S.ITEM_5, S.ITEM_6
    FROM SAT_INTERVALS_STRM_ID S
    JOIN L10_RDV.HUB_INTERVALS H ON S.SHA1_HUB_INTERVAL = H.SHA1_HUB_INTERVAL;

    -- Team Objectives
    INSERT INTO INTERVALS_TEAM_OBJ (ID, MATCH_ID, PLAYER_ID, MINUTE, TEAM_KILLS, TEAM_INHIBITORS, TEAM_TOWERS, TEAM_DRAGONS_FIRE, TEAM_DRAGONS_WATER, TEAM_DRAGONS_EARTH, TEAM_DRAGONS_AIR, TEAM_DRAGONS_CHEMTECH, TEAM_DRAGONS_HEXTECH, TEAM_DRAGONS, TEAM_BARONS, TEAM_VOID_GRUBS, TEAM_HERALDS, TEAM_GOLD_DIFF, TOTAL_OBJECTIVES)
    SELECT
        H.ID, H.MATCH_ID, H.PLAYER_ID, H.MINUTE,
        S.TEAM_KILLS, S.TEAM_INHIBITORS, S.TEAM_TOWERS,
        S.TEAM_DRAGONS_FIRE, S.TEAM_DRAGONS_WATER, S.TEAM_DRAGONS_EARTH, S.TEAM_DRAGONS_AIR,
        S.TEAM_DRAGONS_CHEMTECH, S.TEAM_DRAGONS_HEXTECH, S.TEAM_DRAGONS,
        S.TEAM_BARONS, S.TEAM_VOID_GRUBS, S.TEAM_HERALDS,
        S.TEAM_GOLD_DIFF,
        S.TEAM_DRAGONS + S.TEAM_BARONS + S.TEAM_HERALDS + S.TEAM_VOID_GRUBS
    FROM SAT_INTERVALS_STRM_ID S
    JOIN L10_RDV.HUB_INTERVALS H ON S.SHA1_HUB_INTERVAL = H.SHA1_HUB_INTERVAL;

END;
$$;


-------------------------------------------------------------------------------------------
    -- 2. RESUME TASK
-------------------------------------------------------------------------------------------
ALTER TASK POPULATE_INTERVAL_PARTITIONS RESUME;
